name: lugarun

dependencies:
    - base
    - hakyll
    - filepath
    - pandoc
    - pandoc-types
    - containers
    - time
    - pandoc-types
    - hakyll-sass
    - process
    - bytestring
    - uri-encode
    - text
    - time-locale-compat
    - pandoc-plot

executable:
    main: site.hs
